### ISSUE TITLE
How to do staking?

### ISSUE THREAD

**Issue by immujahidkhan** [Laisky/tact-utils#1]
First of all thank you for the examples.
I want to know how to use staking concept in ton using tact? i was searching in your example but can't find.

Q. I have already deployed JetTon token , now i want to ask how to use that already deployed JetTon token address in staking contract to take JetTon while someone want to stake and also i want to ask is there any approval like in ethereum if yes how to handle it? then after staking if user want to unstake how staking contract transfer JetTon token back to that user again from staking contract?

**Comment by Laisky** [comment]
According to my understanding, staking does not belong to the Jetton standard, but is rather a process of jetton transfer that occurs between a jetton holder and a staking contract.

You transfer Jetton to a staking contract, and then this staking contract determines when it can be refunded based on its internal logic.

Staking-related operations do not need to be implemented within the Jetton Contract.

**Comment by immujahidkhan** [comment]
I know staking does not belong to the Jetton standard, and i know we dont need to implemented within the Jetton Contract, 

My question is how can i utilise JetTon in Staking ( like checking if sender wallet address is in my jettonWallet or not ) as i mention earlier my JetTon contract is already deployed.

**Comment by Laisky** [comment]
Sorry, I didn't get your question. What does "sender's wallet address is in my jettonWallet" mean?

**Comment by immujahidkhan** [comment]
have you ever try staking?

**Comment by Laisky** [comment]
> have you ever try staking?

you may take a look at this https://github.com/Laisky/tact-utils/tree/main/contracts/staking

**Comment by immujahidkhan** [comment]
Thank you so much for your help with the code—your support made all the difference!
