### ISSUE TITLE
frontend transaction sending

### ISSUE THREAD

**Issue by bossonormal215** [Laisky/tact-utils#2]
### How to set the transaction

how to have a button that can send a message to the contract and trigger the "Mint " message for minting an  NFT from the frontend, i already got the TonConnectButton set up on my react app using the "@tonconnect/ui-react" 

`

**Comment by Laisky** [comment]
https://github.com/Laisky/tact-utils/blob/main/web/sample/index.ts#L36-L53

**Comment by bossonormal215** [comment]
Thanks, I've got it and it's working now. But there's a particular problem I'm still struggling to solve.


how can I check if an account is holding an NftItem from my NftCollection. And as well if an account is holding my Jetton. 

Please assist me with this!

**Comment by LeoNore-ort** [comment]
@bossonormal215 Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://chainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Laisky** [comment]
You can use a series of getter methods for Jettons and NFTs to achieve your requirements.

- https://github.com/ton-blockchain/TEPs/blob/master/text/0074-jettons-standard.md#get-methods-1
- https://github.com/ton-blockchain/TEPs/blob/master/text/0062-nft-standard.md#get-methods
